apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nisaba

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  # - ingress.yaml  # Uncomment when ready to expose externally

images:
  - name: ghcr.io/viewrr/nisaba
    newTag: v0.1.0

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: v0.1.0
